stages:
  - validate
  - plan
  - apply

variables:
  TF_ROOT: "."

before_script:
  - terraform --version
  - cd $TF_ROOT
  - terraform init

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan

apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  when: manual
